In [1]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('./Sets/pokemon.csv')

# Filter, where y mask

## Filter

Este dataframe tiene un montón de columnas. Una forma rápida de filtraras es con df.filter

In [98]:
df.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

Le puedes pedir un valor o una lista de valores exactas

In [108]:
df.filter(items = ['name','is_legendary','defense'])

           name  is_legendary  defense
0     Bulbasaur             0       49
1       Ivysaur             0       63
2      Venusaur             0      123
3    Charmander             0       43
4    Charmeleon             0       58
..          ...           ...      ...
796  Celesteela             1      103
797     Kartana             1      131
798    Guzzlord             1       53
799    Necrozma             1      101
800    Magearna             1      115

[801 rows x 3 columns]

O puedes pasar un string similar a lo que buscas

In [99]:
df.filter(like='against_')

,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
0,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
1,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
2,1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
3,0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
4,0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,0.25,0.0,1.0,0.5,0.0,0.5,1.0,0.5,1.0
797,1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,0.25,1.0,1.0,0.5,0.0,0.5,0.5,0.5,0.5
798,2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,0.50,1.0,2.0,1.0,1.0,0.0,1.0,1.0,0.5
799,2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
800,0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,0.50,2.0,0.5,0.5,0.0,0.5,0.5,1.0,1.0

Esa sería una buena forma de accesar todas esas columnas!

## Where

La idea de where es cambiar valores que no cumpan una condición

In [110]:
df[['attack','defense']].where(lambda x: x>100, other='No pasa el límite')

                attack            defense
0    No pasa el límite  No pasa el límite
1    No pasa el límite  No pasa el límite
2    No pasa el límite                123
3    No pasa el límite  No pasa el límite
4    No pasa el límite  No pasa el límite
..                 ...                ...
796                101                103
797                181                131
798                101  No pasa el límite
799                107                101
800  No pasa el límite                115

[801 rows x 2 columns]

Si no le pasas un arugmento a other los valores se vuelven NaNs automáticamente

In [115]:
df[['attack','defense']].where(lambda x: x>100)

     attack  defense
0       NaN      NaN
1       NaN      NaN
2       NaN    123.0
3       NaN      NaN
4       NaN      NaN
..      ...      ...
796   101.0    103.0
797   181.0    131.0
798   101.0      NaN
799   107.0    101.0
800     NaN    115.0

[801 rows x 2 columns]

Combinado con dropna se vuelve un filtro

In [116]:
df[['attack','defense']].where(lambda x: x>100).dropna()

     attack  defense
8     103.0    120.0
75    120.0    130.0
98    130.0    115.0
111   130.0    120.0
126   155.0    120.0
129   155.0    109.0
140   115.0    105.0
207   125.0    230.0
211   150.0    140.0
213   185.0    115.0
231   120.0    120.0
247   164.0    150.0
259   150.0    110.0
302   105.0    125.0
305   140.0    230.0
333   110.0    110.0
366   104.0    105.0
372   145.0    130.0
375   145.0    150.0
382   180.0    160.0
388   109.0    105.0
444   170.0    115.0
449   112.0    118.0
459   132.0    105.0
463   140.0    130.0
469   110.0    130.0
480   105.0    105.0
482   120.0    120.0
485   160.0    110.0
492   120.0    120.0
524   105.0    105.0
525   135.0    130.0
557   105.0    125.0
564   108.0    133.0
588   135.0    105.0
631   109.0    112.0
643   150.0    120.0
651   107.0    122.0
679   110.0    150.0
688   105.0    115.0
696   121.0    119.0
712   117.0    184.0
718   160.0    110.0
720   110.0    120.0
745   140.0    130.0
767   125.0    140.0
783   110.0    125.0
786   130.0    115.0
790   137.0    107.0
793   139.0    139.0
796   101.0    103.0
797   181.0    131.0
799   107.0    101.0

## Mask

Igual que where pero la acción va sobre la condición positiva

In [118]:
df[['attack','defense']].mask(lambda x: x>100, other='muy alto')

       attack   defense
0          49        49
1          62        63
2         100  muy alto
3          52        43
4          64        58
..        ...       ...
796  muy alto  muy alto
797  muy alto  muy alto
798  muy alto        53
799  muy alto  muy alto
800        95  muy alto

[801 rows x 2 columns]

In [117]:
df[['attack','defense']].mask(lambda x: x>100).dropna()

     attack  defense
0      49.0     49.0
1      62.0     63.0
3      52.0     43.0
4      64.0     58.0
6      48.0     65.0
..      ...      ...
782    75.0     90.0
785    85.0     75.0
788    29.0     31.0
792    53.0     47.0
795    89.0     71.0

[565 rows x 2 columns]

---

### np.where

El where de pandas es diferente al where de numpy  
En este caso numpy extrae los índices (si es Serie) o posiciones (si es ndarray) de los elementos que cumplan alguna condición

In [147]:
np.where(df['attack']>100)

(array([  5,   8,  14,  33,  56,  58,  67,  70,  75,  84,  88,  97,  98,
        102, 105, 106, 111, 114, 122, 126, 129, 135, 140, 141, 142, 148,
        149, 159, 207, 209, 211, 213, 216, 223, 231, 243, 247, 249, 253,
        256, 259, 285, 288, 296, 302, 305, 318, 322, 331, 333, 334, 341,
        347, 353, 358, 361, 366, 372, 375, 380, 381, 382, 383, 388, 391,
        397, 404, 407, 408, 418, 427, 429, 444, 447, 449, 453, 459, 460,
        463, 465, 469, 472, 474, 480, 481, 482, 483, 485, 486, 491, 492,
        499, 507, 520, 524, 525, 529, 532, 533, 538, 541, 552, 557, 564,
        565, 566, 570, 588, 603, 610, 611, 613, 619, 620, 622, 624, 625,
        627, 631, 634, 638, 641, 642, 643, 644, 645, 647, 648, 651, 657,
        674, 679, 680, 688, 696, 708, 712, 715, 716, 718, 719, 720, 723,
        726, 732, 734, 739, 744, 745, 749, 753, 759, 762, 765, 767, 774,
        778, 780, 783, 784, 786, 790, 791, 793, 794, 796, 797, 798, 799]),)

Además puede accionar sobre cierto o falso

In [148]:
np.where(df['attack']>100,'Muy alto','Muy bajo')

array(['Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy alto', 'Muy alto', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy alto', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto',
       'Muy bajo', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy bajo',
       'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy alto', 'Muy alto',
       'Muy bajo', 'Muy alto', 'Muy bajo', 'Muy bajo', 'Muy bajo',
       'Muy alto', 'Muy alto', 'Muy bajo', 'Muy alto', 'Muy alto',
       'Muy bajo', 'Muy alto', 'Muy alto', 'Muy alto', 'Muy alto',
       'Muy bajo'], dtype='<U8')

Puede hacer cosas raras como esto:  
Donde ataque sea mayor a defensa pon el valor de ataque. Donde sea igual o menor pon el nombre del pokemon

In [150]:
np.where(df.attack > df.defense, df.attack, df.name)

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 52, 64, 104, 'Squirtle',
       'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree', 35,
       'Kakuna', 150, 45, 60, 'Pidgeot', 56, 71, 60, 90, 60, 95, 55, 85,
       'Sandshrew', 'Sandslash', 'Nidoran♀', 'Nidorina', 92, 57, 72, 102,
       'Clefairy', 'Clefable', 41, 'Ninetales', 45, 70, 45, 80, 'Oddish',
       'Gloom', 'Vileplume', 70, 95, 55, 65, 55, 100, 'Meowth', 'Persian',
       52, 82, 80, 105, 70, 110, 50, 'Poliwhirl', 'Poliwrath', 20, 35,
       'Alakazam', 80, 100, 130, 75, 90, 105, 40, 70, 'Geodude',
       'Graveler', 'Golem', 85, 100, 'Slowpoke', 'Slowbro', 'Magnemite',
       'Magneton', 90, 85, 110, 'Seel', 'Dewgong', 80, 105, 'Shellder',
       'Cloyster', 35, 50, 'Gengar', 'Onix', 48, 73, 105, 130, 'Voltorb',
       'Electrode', 'Exeggcute', 105, 'Cubone', 'Marowak', 120, 105,
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 130, 'Chansey',
       'Tangela', 125, 'Horsea', 'Seadra', 67, 92, 'Staryu', 'Starmie',
       'Mr. Mime', 110, 50, 83, 95, 155, 100, 'Magikarp', 155, 85,
       'Ditto', 55, 65, 65, 130, 'Porygon', 'Omanyte', 'Omastar',
       'Kabuto', 115, 135, 110, 'Articuno', 90, 100, 64, 84, 134, 150,
       'Mew', 'Chikorita', 'Bayleef', 'Meganium', 52, 64, 84, 65,
       'Croconaw', 105, 46, 76, 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian',
       60, 90, 90, 'Chinchou', 'Lanturn', 40, 'Cleffa', 30, 'Togepi',
       'Togetic', 50, 75, 'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom',
       'Marill', 'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip',
       'Skiploom', 'Jumpluff', 70, 'Sunkern', 75, 65, 'Wooper',
       'Quagsire', 65, 'Umbreon', 85, 'Slowking', 'Misdreavus', 72,
       'Wobbuffet', 80, 'Pineco', 'Forretress', 'Dunsparce', 'Gligar',
       'Steelix', 80, 120, 95, 150, 'Shuckle', 185, 95, 80, 130, 'Slugma',
       'Magcargo', 50, 100, 'Corsola', 65, 105, 55, 'Mantine', 'Skarmory',
       60, 'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 95,
       'Smeargle', 'Tyrogue', 'Hitmontop', 30, 63, 75, 'Miltank',
       'Blissey', 85, 115, 'Suicune', 64, 84, 164, 'Lugia', 130, 'Celebi',
       45, 65, 110, 60, 85, 160, 70, 85, 150, 55, 90, 'Zigzagoon', 70, 45,
       'Silcoon', 70, 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 70, 100, 55, 85, 'Wingull', 'Pelipper', 'Ralts',
       'Kirlia', 85, 'Surskit', 'Masquerain', 'Shroomish', 130, 'Slakoth',
       'Vigoroth', 160, 'Nincada', 90, 90, 51, 71, 91, 60, 120, 'Azurill',
       'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron',
       'Lairon', 'Aggron', 'Meditite', 100, 45, 'Manectric', 50, 'Minun',
       'Volbeat', 'Illumise', 60, 'Gulpin', 'Swalot', 90, 140, 70, 90, 60,
       120, 'Torkoal', 'Spoink', 'Grumpig', 'Spinda', 100, 70, 100, 85,
       115, 'Swablu', 'Altaria', 115, 100, 'Lunatone', 95, 48, 78, 80,
       120, 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 95, 125, 'Feebas',
       'Milotic', 'Castform', 90, 75, 165, 'Duskull', 'Dusclops',
       'Tropius', 'Chimecho', 150, 'Wynaut', 'Snorunt', 120, 'Spheal',
       'Sealeo', 'Walrein', 'Clamperl', 'Huntail', 'Gorebyss',
       'Relicanth', 'Luvdisc', 75, 'Shelgon', 145, 'Beldum', 'Metang',
       'Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias', 130, 150,
       180, 180, 'Jirachi', 95, 68, 89, 109, 58, 78, 104, 'Piplup',
       'Prinplup', 'Empoleon', 55, 75, 120, 45, 85, 'Kricketot', 85, 65,
       85, 120, 'Budew', 70, 125, 165, 'Shieldon', 'Bastiodon', 'Burmy',
       'Wormadam', 94, 'Combee', 'Vespiquen', 'Pachirisu', 65, 105,
       'Cherubi', 'Cherrim', 'Shellos', 83, 100, 50, 80, 66, 136,
       'Mismagius', 125, 55, 82, 'Chingling', 63, 93, 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 65, 'Spiritomb', 70,
       90, 170, 85, 70, 145, 'Hippopotas', 'Hippowdon', 'Skorupi',
       'Drapion', 61, 106, 100, 'Finneon', 'Lumineon', 'Mantyke', 62, 132,
       120, 'Magnezone', 'Lickilicky', 140, 'Tangrowth', 123, 95,
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor', 130, 80,
       165, 'Probopass', 'Dusknoir', 80, 'Rotom', 'Uxie', 'Mesprit', 125,
       'Dialga', 120, 'Heatran', 160, 120, 'Cresselia', 'Phione',
       'Manaphy', 'Darkrai', 103, 'Arceus', 'Victini', 'Snivy', 'Servine',
       'Serperior', 63, 93, 123, 55, 75, 100, 55, 85, 60, 80, 110, 50, 88,
       53, 98, 53, 98, 53, 98, 'Munna', 'Musharna', 55, 77, 115, 60, 100,
       'Roggenrola', 'Boldore', 135, 45, 57, 85, 135, 'Audino', 80, 105,
       140, 50, 65, 95, 100, 125, 'Sewaddle', 'Swadloon', 103, 'Venipede',
       'Whirlipede', 100, 'Cottonee', 'Whimsicott', 'Petilil',
       'Lilligant', 92, 72, 82, 117, 90, 'Darmanitan', 86, 'Dwebble',
       'Crustle', 75, 'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus',
       'Tirtouga', 'Carracosta', 112, 140, 'Trubbish', 95, 65, 105, 50,
       95, 'Gothita', 'Gothorita', 'Gothitelle', 'Solosis', 'Duosion',
       'Reuniclus', 'Ducklett', 87, 'Vanillite', 'Vanillish', 95, 60, 100,
       75, 75, 135, 55, 85, 'Frillish', 'Jellicent', 'Alomomola',
       'Joltik', 77, 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 55, 85, 115, 'Elgyem', 'Beheeyem', 'Litwick',
       'Lampent', 'Chandelure', 87, 117, 147, 70, 130, 'Cryogonal',
       'Shelmet', 70, 'Stunfisk', 85, 125, 120, 74, 124, 85, 125, 110, 83,
       123, 'Vullaby', 'Mandibuzz', 97, 'Durant', 65, 85, 105, 85,
       'Volcarona', 'Cobalion', 129, 90, 100, 105, 120, 150, 145, 120,
       'Keldeo', 128, 120, 'Chespin', 'Quilladin', 'Chesnaught', 45, 59,
       'Delphox', 56, 63, 145, 'Bunnelby', 'Diggersby', 50, 73, 81,
       'Scatterbug', 'Spewpa', 52, 'Litleo', 'Pyroar', 'Flabébé',
       'Floette', 'Florges', 65, 100, 82, 124, 80, 'Espurr', 'Meowstic',
       'Honedge', 'Doublade', 150, 'Spritzee', 'Aromatisse', 'Swirlix',
       'Slurpuff', 54, 92, 'Binacle', 'Barbaracle', 'Skrelp', 'Dragalge',
       'Clauncher', 'Clawitzer', 38, 55, 89, 121, 59, 77, 'Sylveon', 92,
       58, 'Carbink', 50, 75, 100, 'Klefki', 70, 110, 'Pumpkaboo',
       'Gourgeist', 'Bergmite', 'Avalugg', 'Noibat', 'Noivern', 131, 131,
       'Zygarde', 160, 160, 'Volcanion', 'Rowlet', 'Dartrix', 107, 65, 85,
       115, 'Popplio', 'Brionne', 'Primarina', 75, 85, 120, 70, 110, 62,
       'Charjabug', 'Vikavolt', 82, 132, 'Oricorio', 45, 'Ribombee', 65,
       115, 140, 'Mareanie', 'Toxapex', 100, 125, 'Dewpider', 'Araquanid',
       55, 105, 'Morelull', 'Shiinotic', 44, 64, 75, 125, 'Bounsweet',
       'Steenee', 120, 'Comfey', 'Oranguru', 120, 'Wimpod', 'Golisopod',
       'Sandygast', 'Palossand', 'Pyukumuku', 'Type: Null', 'Silvally',
       100, 115, 'Turtonator', 98, 90, 105, 'Drampa', 131, 'Jangmo-o',
       'Hakamo-o', 'Kommo-o', 115, 85, 130, 'Tapu Fini', 'Cosmog',
       'Cosmoem', 137, 113, 53, 'Buzzwole', 137, 89, 'Celesteela', 181,
       101, 107, 'Magearna'], dtype=object)